// project images
export const images = [
  {
    id: 1,
    name: "Full Stack Taco Shop",
    alt: "FS Taco Shop screenshot",
    src: "../../../../../public/taco-shop.png",
    deployUrl: "https://quiet-beach-11732.herokuapp.com",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/taco-shop",
    githubLabel: "Go to GitHub Repository",
  },
  {
    id: 2,
    name: "Workout Planner",
    alt: "Workout Planner screenshot",
    src: "../../../../../public/workout-planner.png",
    deployUrl: "https://quiet-forest-44254.herokuapp.com",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/workout-planner",
    githubLabel: "Go to GitHub Repository",
  },
  {
    id: 3,
    name: "Jokinator",
    alt: "Jokinator screenshot",
    src: "../../../../../assets/projects/jokinator.png",
    deployUrl: "https://amiedawn.github.io/jokinator",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/jokinator",
    githubLabel: "Go to GitHub Repository",
  },
  {
    id: 4,
    name: "Weather Dashboard",
    alt: "Weather Dashboard screenshot",
    src: "../../../../../assets/projects/weather-dashboard.png",
    deployUrl: "https://amiedawn.github.io/weather-dashboard/",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/weather-dashboard",
    githubLabel: "Go to GitHub Repository",
  },
  {
    id: 5,
    name: "Tech Blog",
    alt: "Tech Blog screenshot",
    src: "../../../../../assets/projects/tech-blog.png",
    deployUrl: "https://morning-wave-37012.herokuapp.com",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/tech-blog",
    githubLabel: "Go to GitHub Repository",
  },
  {
    id: 6,
    name: "Code Quiz",
    alt: "Code Quiz screenshot",
    src: "../../../../../assets/projects/code-quiz.png",
    deployUrl: "https://amiedawn.github.io/quiz-app",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/quiz-app",
    githubLabel: "Go to GitHub Repository",
  },
  {
    id: 7,
    name: "Work Portfolio",
    alt: "Work Portfolio screenshot",
    src: "../../../../../assets/projects/work-portfolio.png",
    deployUrl: "https://amiedawn.github.io/work-portfolio",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/work-portfolio",
    githubLabel: "Go to GitHub Repository",
  },
];

