// project images and data
export const images = [
  {
    id: 1,
    name: "Restaurant Ordering Site",
    alt: "FS Taco Shop screenshot",
    src: "../../../../../public/taco-shop.png",
    deployUrl: "https://quiet-beach-11732.herokuapp.com",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/taco-shop",
    githubLabel: "Go to GitHub Repository",
    skills: "JavaScript, React.js, MongoDB, Express.js, Node.js, JWT",
  },
  {
    id: 2,
    name: "App to View, Review, and Save Workout Classes",
    alt: "Workout Planner screenshot",
    src: "../../../../../public/workout-planner.png",
    deployUrl: "https://quiet-forest-44254.herokuapp.com",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/workout-planner",
    githubLabel: "Go to GitHub Repository",
    skills: "JavaScript ",
  },
  {
    id: 3,
    name: "See Dad Jokes and Share on Twitter",
    alt: "Jokinator screenshot",
    src: "../../../../../assets/projects/jokinator.png",
    deployUrl: "https://amiedawn.github.io/jokinator",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/jokinator",
    githubLabel: "Go to GitHub Repository",
    skills: "JavaScript ",
  },
  {
    id: 4,
    name: "View Current Weather and 5-Day Forecast",
    alt: "Weather Dashboard screenshot",
    src: "../../../../../assets/projects/weather-dashboard.png",
    deployUrl: "https://amiedawn.github.io/weather-dashboard/",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/weather-dashboard",
    githubLabel: "Go to GitHub Repository",
    skills: "JavaScript ",
  },
  {
    id: 5,
    name: "Blog Site",
    alt: "Tech Blog screenshot",
    src: "../../../../../assets/projects/tech-blog.png",
    deployUrl: "https://morning-wave-37012.herokuapp.com",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/tech-blog",
    githubLabel: "Go to GitHub Repository",
    skills: "JavaScript ",
  },
  {
    id: 6,
    name: "Quiz that Counts Down and Tracks High Scores",
    alt: "Code Quiz screenshot",
    src: "../../../../../assets/projects/code-quiz.png",
    deployUrl: "https://amiedawn.github.io/quiz-app",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/quiz-app",
    githubLabel: "Go to GitHub Repository",
    skills: "JavaScript ",
  },
  {
    id: 7,
    name: "Search and Save Books to a List",
    alt: "Book Hunt screenshot",
    src: "../../../../../assets/projects/work-portfolio.png",
    deployUrl: "https://blooming-dawn-50560.herokuapp.com/",
    deployLabel: "Visit Website",
    githubUrl: "https://github.com/amiedawn/my-book-search/tree/master",
    githubLabel: "Go to GitHub Repository",
    skills: "JavaScript ",
  },
];

